pipeline {
    agent { label 'slave1' }   // change to your node label

    tools {
        maven 'MAVEN_HOME'
        jdk 'JAVA_HOME'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/BhargavApkr/demo-repo.git'
            }
        }

        stage('Build') {
            steps {
                dir('simple-java-app') {
                    sh 'mvn clean package -DskipTests=false'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('simple-java-app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'simple-java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'simple-java-app/target/*.jar', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo "Deployment placeholder"
            }
        }
    }

    post {
        success { echo "Pipeline completed successfully!" }
        failure { echo "Pipeline failed!" }
    }
}
